"""Export sprites to the game's palette-indexed TypeScript sprite data (ADR 0002).

    art.py export [--root DIR] [MODULE ...] [--out DIR]

Each manifest "exports" entry becomes one TypeScript module:
    "rexi": {"sprites": ["frames/**/*.png"], "format": "rle", "out": "src/render/art/generated",
             "data": {"anims": "frames/anim.json", "armPivots": "parts/arm/pivots.json"}}

- format "rows" writes `defineSprite(K, ['..kk..', ...])` with one fixed pixel-text code per
  palette colour (pixtext.CODES): readable and diffable, for small sprites and icons.
- format "rle" writes `decodeSprite({ width, height, colors, data })` (src/render/sprite-data.ts):
  run-length palette indices in base64, for large frames and scene layers.
Both give an ordinary SpriteDef that the SpriteBank rasterises, so the renderer's determinism
rule holds. Sprite keys are paths relative to the common folder of the matched files, without
.png ('idle/00'). `data` embeds JSON files (animation tables, part pivots) as `as const`
objects. The module is formatted with Prettier when it lands inside the repo.

Every pixel must be opaque or clear and on the master palette: the export refuses anything
else (run art.py audit for the full report).
"""
import base64
import glob
import json
import os
import subprocess

import numpy as np
from PIL import Image

from palette import NAME_OF, ROOT, rgb2hex
from pixtext import CODE_OF

HEADER = ("// Generated by `npm run art -- export` from {src} (exports.{name}).\n"
          "// Do not edit by hand: change the art and export again (ADR 0002, scripts/art/README.md).\n")


class ExportError(Exception):
    pass


def indexed(sp, where=""):
    """RGBA -> (colour names in first-use order, int array: 0 clear, i = names[i - 1])."""
    a = sp[..., 3]
    if not set(np.unique(a).tolist()) <= {0, 255}:
        raise ExportError(f"{where}: partial alpha (ADR 0002: dither instead)")
    names, idx = [], np.zeros(a.shape, int)
    for y, x in zip(*np.nonzero(a)):
        h = rgb2hex(sp[y, x])
        if h not in NAME_OF:
            raise ExportError(f"{where}: {h} at ({x}, {y}) is not a master-palette colour")
        n = NAME_OF[h]
        if n not in names:
            names.append(n)
        idx[y, x] = names.index(n) + 1
    return names, idx


def encode_rle(idx):
    """Row-major runs as byte pairs (index, length - 1), runs of at most 256, base64."""
    flat = idx.ravel().tolist()
    out = bytearray()
    i = 0
    while i < len(flat):
        v, n = flat[i], 1
        while i + n < len(flat) and flat[i + n] == v and n < 256:
            n += 1
        out += bytes((v, n - 1))
        i += n
    return base64.b64encode(bytes(out)).decode("ascii")


def decode_rle(data, width, height):
    raw = base64.b64decode(data)
    flat = []
    for v, n in zip(raw[0::2], raw[1::2]):
        flat += [v] * (n + 1)
    if len(flat) != width * height:
        raise ExportError(f"RLE holds {len(flat)} pixels, expected {width * height}")
    return np.array(flat, int).reshape(height, width)


def rows_of(names, idx):
    codes = ["."] + [CODE_OF[n] for n in names]
    return ["".join(codes[v] for v in row) for row in idx.tolist()]


def _ts_str(s):
    return "'" + s.replace("\\", "\\\\").replace("'", "\\'") + "'"


def module_source(name, src_label, sprites, fmt, data, render_import):
    """sprites: [(key, RGBA)]; data: {identifier: json value}."""
    used, body = [], []
    for key, sp in sprites:
        names, idx = indexed(sp, key)
        if fmt == "rows":
            used += [n for n in names if n not in used]
            rows = ", ".join(_ts_str(r) for r in rows_of(names, idx))
            body.append(f"  {_ts_str(key)}: defineSprite(K, [{rows}]),")
        else:
            cols = ", ".join(_ts_str(n) for n in names)
            body.append(f"  {_ts_str(key)}: decodeSprite({{ width: {idx.shape[1]}, height: {idx.shape[0]}, "
                        f"colors: [{cols}], data: {_ts_str(encode_rle(idx))} }}),")
    lines = [HEADER.format(src=src_label, name=name)]
    if fmt == "rows":
        lines.append(f"import {{ masterPalette as P }} from '{render_import}/palette';")
        lines.append(f"import {{ defineSprite, type SpriteDef }} from '{render_import}/sprite';\n")
        keys = ", ".join(f"{_ts_str(CODE_OF[n])}: P.{n}" for n in sorted(used, key=lambda n: CODE_OF[n]))
        lines.append(f"const K = {{ {keys} }};\n")
    else:
        lines.append(f"import type {{ SpriteDef }} from '{render_import}/sprite';")
        lines.append(f"import {{ decodeSprite }} from '{render_import}/sprite-data';\n")
    lines.append("export const sprites = {")
    lines += body
    lines.append("} satisfies Record<string, SpriteDef>;")
    for ident, value in data.items():
        lines.append(f"\nexport const {ident} = {json.dumps(value)} as const;")
    return "\n".join(lines) + "\n"


def collect(project, patterns):
    files = []
    for pat in patterns:
        files += sorted(glob.glob(project.path(pat), recursive=True))
    files = [f for f in dict.fromkeys(files) if f.endswith(".png")]
    if not files:
        return []
    base = os.path.commonpath([os.path.dirname(f) for f in files])
    return [(os.path.splitext(os.path.relpath(f, base))[0].replace(os.sep, "/"), f) for f in files]


def run(project, only=(), out_override=None, log=print):
    written = []
    for name, cfg in project.exports.items():
        if only and name not in only:
            continue
        found = collect(project, cfg["sprites"])
        if not found:
            log(f"-- exports.{name}: no sprites match {cfg['sprites']}")
            continue
        out_dir = os.path.abspath(out_override or os.path.join(ROOT, cfg.get("out", os.path.join(project.rel, "build", "ts"))))
        os.makedirs(out_dir, exist_ok=True)
        render_import = os.path.relpath(os.path.join(ROOT, "src", "render"), out_dir).replace(os.sep, "/")
        if not render_import.startswith("."):
            render_import = "./" + render_import
        sprites = [(k, np.asarray(Image.open(f).convert("RGBA"))) for k, f in found]
        data = {ident: json.load(open(project.path(p))) for ident, p in cfg.get("data", {}).items()}
        src = module_source(name, f"{project.rel}/sheets.json", sprites, cfg.get("format", "rows"), data, render_import)
        path = os.path.join(out_dir, name + ".ts")
        open(path, "w").write(src)
        if os.path.commonpath([path, ROOT]) == ROOT:
            subprocess.run(["npx", "prettier", "--write", path], cwd=ROOT, capture_output=True)
        written.append(path)
        log(f"exports.{name}: {len(sprites)} sprites ({cfg.get('format', 'rows')}) -> {os.path.relpath(path, ROOT)}")
    return written
