"""Rexi, animated in code from the master and the generated key poses (manus-garden's Art/anim ideas).

Every frame is layered from parts, never redrawn freehand:
  * upper body  the master's head, torso and tattooed near arm, pixel for pixel (no boiling);
                only the hurt frames keep their key's own head (a different expression);
  * lower body  the robe's lower half, trousers and boots from a key pose (generated by editing
                the master against a pose guide), aligned to the master by the slot it was drawn
                in, refined by matching the head;
  * aiming arm  the far arm, cut from arm_v1 (an edit of the master with the arm straight out),
                holding the Mazo Automático, pre-rotated with RotSprite into 9 angles (-90..90 in
                22.5 degree steps) and mirrored for facing left: 16 directions;
  * shoulder    the robe's lapel from arm_v1, drawn over the arm's root at every angle.
Facing left mirrors the frame and moves the sleeve tattoo so it stays on Rexi's left arm: the
near arm loses it (detattoo) and the aiming arm wears it.

    from rexi_rig import Rig
    rig = Rig(); frame = rig.frame("run", 0, facing=1)
"""
import json
import os
import sys

import numpy as np
from PIL import Image

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from palette import ROOT  # noqa: E402
from pixtext import RGB, INV, from_text, paint  # noqa: E402
from rotsprite import rotate  # noqa: E402

PIPE = os.path.join(ROOT, "reference", "manu-pipeline")
CLEAN = os.path.join(PIPE, "clean")

CANVAS = (120, 100)                # export canvas: room for the arm and the muzzle flash in every direction
BODY = (37, 20)                    # master frame (48x72) origin on the canvas (torso centre on column 60)
FEET = BODY[1] + 69                # baseline row on the canvas (soles)
MASTER_LOCAL = (10, 5)             # master_b local (0, 0) inside the master frame
SLOT_W, SHEET_GROUND = 60, 100     # key sheets: 4 slots of 60 cells, ground row 100
MASTER_BBOX_W, MASTER_H = 27, 65   # master copy as pasted into every edit sheet
WAIST = 37                         # frame rows <= WAIST come from the master (upper body lock)
PIVOT = (33, 20)                   # aiming arm's shoulder pivot in frame coords (facing right)
ANGLES = [-90, -67.5, -45, -22.5, 0, 22.5, 45, 67.5, 90]

SKIN = set("abcde")
TATTOO_INK = set("MNL")
ROBE = set("knrR")


def rgba(code):
    return np.array(RGB[code] + (255,), np.uint8)


def code_at(sp, x, y):
    if not (0 <= y < sp.shape[0] and 0 <= x < sp.shape[1]) or sp[y, x, 3] == 0:
        return "."
    return INV.get(tuple(int(v) for v in sp[y, x, :3]), "?")


def load(name):
    return np.asarray(Image.open(os.path.join(CLEAN, name + ".png")).convert("RGBA")).copy()


def blit(dst, src, x0, y0, mask=None):
    """Alpha-stamp src onto dst at integer (x0, y0)."""
    h, w = src.shape[:2]
    for y in range(h):
        Y = y0 + y
        if not 0 <= Y < dst.shape[0]:
            continue
        for x in range(w):
            X = x0 + x
            if 0 <= X < dst.shape[1] and src[y, x, 3] and (mask is None or mask[y, x]):
                dst[Y, X] = src[y, x]
    return dst


# ------------------------------------------------------------------ the Mazo Automático
# A gavel held like a pistol: the head is the barrel (wood with two brass rings and a light
# striking face at the muzzle), the handle is the grip and pokes out under the fist.
# Drawn facing right at 0 degrees, in the arm sprite's coordinates (see Rig._arm()).
MAZO = [          # x 0..2 sit under the fist
    "..kkk......kkk.",
    ".kOhOkkkkkkOhOk",
    ".kOOOyOOOOyOOOk",
    ".kNNNYNNNNYNNhk",
    ".kNNNyNNNNyNNOk",
    ".kMMMyMMMMyMMNk",
    ".kMMMkkkkkkMMMk",
    "..kkk......kkk.",
]
MAZO_HANDLE = [   # the grip, poking out under the fist
    "kOk",
    "kNk",
    "kMk",
    ".k.",
]


def hand_pass(sp):
    """The master's rule-based hand pass (fix_master.py), applied to a key pose: interior outline
    black in the robe becomes `night`, boot leather1 inside the boot becomes leather2."""
    out = sp.copy()
    h, w = sp.shape[:2]
    for y in range(h):
        for x in range(w):
            c = code_at(sp, x, y)
            if c not in "kL":
                continue
            ns = [code_at(sp, x + dx, y + dy) for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))]
            if c == "k" and all(n in ROBE for n in ns):
                out[y, x] = rgba("n")
            elif c == "L" and "." not in ns and code_at(sp, x, y + 1) != "k" and y > h - 16:
                out[y, x] = rgba("M")
    return out


def despeckle(sp):
    """Drop lone pixels (no opaque 8-neighbour): crumbs left by the key poses' far fists."""
    a = sp[..., 3] > 0
    p = np.pad(a, 1)
    n = sum(p[1 + dy:1 + dy + a.shape[0], 1 + dx:1 + dx + a.shape[1]] for dy in (-1, 0, 1) for dx in (-1, 0, 1)) - a
    out = sp.copy()
    out[a & (n == 0)] = 0
    return out


class Rig:
    def __init__(self):
        self.pos = json.load(open(os.path.join(CLEAN, "positions.json")))
        self.master = np.asarray(Image.open(os.path.join(PIPE, "master_side.png")).convert("RGBA")).copy()
        self.upper, self.upper_plain = self._upper()
        self.arm, self.arm_pivot, self.cap = self._arm()
        self.arms = {}                         # (angle, inked) -> (sprite, pivot)
        self.keys = {}

    # -------------------------------------------------------------- master-derived parts
    def _upper(self):
        """The master frame minus the far fist (replaced by the aiming arm). Returns the inked
        version and the plain one (no sleeve on the near arm, for facing left)."""
        m = self.master.copy()
        for y in range(34, 47):                # far fist sticking out past the robe's front edge
            for x in range(34, 40):
                if code_at(m, x, y) in SKIN | {"M", "L"}:
                    m[y, x] = 0
        plain = m.copy()
        # detattoo: ink inside the near arm (frame x 10..24, rows 18..47) becomes the skin around it
        for _ in range(2):
            src = plain.copy()
            for y in range(18, 48):
                for x in range(10, 25):
                    c = code_at(src, x, y)
                    if c not in TATTOO_INK:
                        continue
                    ns = [code_at(src, x + dx, y + dy) for dx, dy in ((1, 0), (-1, 0), (0, 1), (0, -1))]
                    if "." in ns or any(n in ROBE for n in ns):
                        continue              # silhouette outline of the arm: keep
                    skin = [n for n in ns if n in SKIN]
                    if skin:
                        plain[y, x] = rgba(max(set(skin), key=skin.count))
        return m, plain

    def _arm(self):
        """The aiming arm from arm_forward_a, straight out to the right, plus the Mazo, as a
        sprite with its shoulder pivot; and the lapel cap that covers the arm's root."""
        src = load("arm_forward_a")             # same local coords as the master (edit in place)
        lx, ly = MASTER_LOCAL
        ox, oy = 28, 13                         # arm sprite (0, 0) in frame coords
        H, W = 24, 56
        arm = np.zeros((H, W, 4), np.uint8)
        for y in range(10, 22):                 # skin of the arm past the lapel (local x >= 25)
            for x in range(25, src.shape[1]):
                if src[y, x, 3] and code_at(src, x, y) in SKIN | {"M"}:
                    arm[y + ly - oy, x + lx - ox] = src[y, x]
        # root: repeat the first column under the lapel so rotation never opens a gap
        root = 25 + lx - ox
        for x in range(root - 5, root):
            arm[:, x] = arm[:, root]
        # the Mazo: head in front of the fist (its first 3 columns under it), grip below
        fist_l, fist_t = 54 - ox, 17 - oy        # fist's left / top on the arm sprite
        fist = arm.copy()
        blit(arm, from_text(MAZO), fist_l + 3, fist_t - 1)
        blit(arm, fist[:, :fist_l + 6], 0, 0)    # the fist's knuckles stay in front of the head
        blit(arm, from_text(MAZO_HANDLE), fist_l + 1, fist_t + 6)
        # lapel cap: robe pixels of arm_forward_a over the root (local x 18..24)
        cap = np.zeros_like(self.master)
        for y in range(9, 22):
            for x in range(18, 25):
                if src[y, x, 3] and code_at(src, x, y) in ROBE:
                    cap[y + ly, x + lx] = src[y, x]
        self.muzzle_reach = (fist_l + 3 + 15) - (PIVOT[0] - ox)
        return arm, (PIVOT[0] - ox, PIVOT[1] - oy), cap

    def ink(self, arm):
        """Paint a small sleeve tattoo (lion's face over a row of columns) on the arm's upper
        segment: used when the aiming arm is Rexi's left arm (facing left)."""
        a = arm.copy()
        px, py = self.arm_pivot
        lion = [".MMM.", "MdMdM", "MdddM", ".MMM."]
        cols = ["MMM", "MdM"]
        paint(a, px + 3, py - 3, lion)
        paint(a, px + 9, py - 1, cols)
        return a

    def arm_at(self, angle, inked=False):
        key = (angle, inked)
        if key not in self.arms:
            base = self.ink(self.arm) if inked else self.arm
            if angle in (0, 90, -90):
                self.arms[key] = rotate(base, angle, self.arm_pivot) if angle else (base, self.arm_pivot)
            else:   # rotate from the nearer of 0 / +-90 so the turn stays small
                near = 90 * round(angle / 90)
                b, p = rotate(base, near, self.arm_pivot) if near else (base, self.arm_pivot)
                self.arms[key] = rotate(b, angle - near, p)
        return self.arms[key]

    # -------------------------------------------------------------- key poses
    def key(self, name):
        """A key pose placed in frame coordinates: (sprite on a frame-sized canvas, head offset)."""
        if name in self.keys:
            return self.keys[name]
        p = self.pos[name]
        sp = hand_pass(load(name))
        slot = {"key_contact": 0, "key_passing": 1, "key_jump": 2, "key_hurt": 3,
                "key_downA": 0, "key_contactB": 1, "key_downB": 2, "key_passingB": 3,
                "key_rise": 0, "key_fall": 1, "key_land": 2, "key_hurt2": 3}[name]
        mx = slot * SLOT_W + SLOT_W // 2 - MASTER_BBOX_W // 2      # master copy's left on the sheet
        my = SHEET_GROUND - MASTER_H
        fx = p["x"] - mx + MASTER_LOCAL[0]                          # key's left in frame coords
        fy = p["y"] - my + MASTER_LOCAL[1]
        H, W = self.master.shape[:2]
        frame = np.zeros((H + 60, W + 60, 4), np.uint8)               # 30 px margin all round
        blit(frame, sp, fx + 30, fy + 30)
        self.keys[name] = (frame, (fx, fy))
        return self.keys[name]

    def head_offset(self, name):
        """(dx, dy) the key's head sits at relative to the master's, by best match."""
        frame, _ = self.key(name)
        best = None
        for dy in range(-24, 10):
            for dx in range(-6, 7):
                s = 0
                for y in range(5, 17):
                    for x in range(18, 31):
                        if not self.master[y, x, 3]:
                            continue
                        Y, X = y + dy + 30, x + dx + 30
                        if frame[Y, X, 3] and (frame[Y, X, :3] == self.master[y, x, :3]).all():
                            s += 1
                if best is None or s > best[0]:
                    best = (s, dx, dy)
        return best[1], best[2]

    # -------------------------------------------------------------- composition
    def compose(self, key=None, bob=0, own_upper=False, angle=0, recoil=0, flash=0, facing=1,
                breath=0, blink=False, shorten=0, lift=0, arm_shift=(0, 0)):
        """One frame on the export canvas. key: key pose for the lower body (None = master's);
        bob: upper body rows down (+) or up (-); own_upper: keep the key's own head and torso
        (hurt); angle: aiming-arm angle in degrees (facing right); recoil: px pulled back along
        the aim; flash: muzzle flash size 0..2; shorten: rows removed from a key's legs (the
        model drew the stretched air poses' legs too long); lift: whole frame up (+) in px."""
        W, H = CANVAS
        bx, by = BODY
        out = np.zeros((H, W, 4), np.uint8)
        inked = facing == 1
        upper = self.upper if inked else self.upper_plain
        if key:
            kf, _ = self.key(key)
            hx, hy = self.head_offset(key)
            dx, dy = -hx, bob - hy
            if own_upper:
                dx, dy = 0, bob
            M = 30
            sp = kf.copy()
            if shorten:
                sp = self._shorten(sp, shorten, top=WAIST + 4 + M + hy)
            for y in range(sp.shape[0]):
                for x in range(sp.shape[1]):
                    if not sp[y, x, 3]:
                        continue
                    X, Y = x - M + dx, y - M + dy           # frame coords
                    c = code_at(sp, x, y)
                    if not own_upper:
                        if Y <= WAIST + bob:
                            # above the waist only the robe streaming out behind him survives
                            if not (c in ROBE and X < 20 and not self._upper_on(X, Y - bob)):
                                continue
                        elif X >= 33 and Y <= 50 + bob and c in SKIN | {"M", "L"}:
                            continue                         # the key's far fist: the aiming arm replaces it
                    elif X >= 31 + dx and 20 <= Y <= 52 and c in SKIN | {"M", "L"}:
                        continue                             # hurt: the key's far fist
                    if 0 <= X + bx < W and 0 <= Y + by - lift < H:
                        out[Y + by - lift, X + bx] = sp[y, x]
        else:
            for y in range(upper.shape[0]):
                for x in range(upper.shape[1]):
                    if upper[y, x, 3] and y > WAIST and not self._near_arm(x, y):
                        out[y + by - lift, x + bx] = upper[y, x]
        if not own_upper:
            up = upper.copy()
            if breath:
                up = self._breath(up)
            if blink:
                up = self._blink(up)
            for y in range(up.shape[0]):
                for x in range(up.shape[1]):
                    if up[y, x, 3] and (y <= WAIST or self._near_arm(x, y)):
                        Y = y + bob + by - lift
                        if 0 <= Y < H:
                            out[Y, x + bx] = up[y, x]
        # aiming arm, then the lapel over its root
        sx, sy = (0, -1) if breath else (0, 0)
        if own_upper and key:                     # the shoulder leans back with the key's torso
            hx, hy = self.head_offset(key)
            sx, sy = int(round(hx * 0.6)) + arm_shift[0], hy + arm_shift[1]
        arm, (apx, apy) = self.arm_at(angle, inked=not inked)
        th = np.radians(angle)
        rx, ry = -recoil * np.cos(th), recoil * np.sin(th)
        ax = int(round(bx + PIVOT[0] + sx + rx - apx))
        ay = int(round(by + PIVOT[1] + sy + bob - lift + ry - apy))
        blit(out, arm, ax, ay)
        blit(out, self.cap, bx + sx, by + sy + bob - lift)
        if flash:
            self._muzzle(out, angle, ax + apx, ay + apy, flash)
        out = despeckle(out)
        if facing == -1:
            out = out[:, ::-1].copy()
        return out

    def _upper_on(self, x, y):
        return 0 <= y < self.upper.shape[0] and 0 <= x < self.upper.shape[1] and self.upper[y, x, 3] > 0

    def _near_arm(self, x, y):
        """Master pixels of the hanging near arm below the waist (skin, ink and their outline)."""
        if not (10 <= x <= 25 and WAIST < y <= 47):
            return False
        c = code_at(self.master, x, y)
        if c in SKIN or c in TATTOO_INK or c == "O":
            return True
        if c == "k":   # outline: only where it borders the arm
            return any(code_at(self.master, x + ddx, y + ddy) in SKIN for ddx, ddy in ((1, 0), (-1, 0), (0, 1), (0, -1)))
        return False

    def _shorten(self, sp, n, top):
        """Remove n rows between `top` and the boots, the ones most like the row below them
        (manus-garden's pixelize.shorten); everything above slides down."""
        sp = sp.copy()
        for _ in range(n):
            ys = np.nonzero(sp[..., 3].any(1))[0]
            bot = ys.max() - 8
            best = None
            for y in range(top, bot):
                d = (np.abs(sp[y].astype(int) - sp[y + 1].astype(int)).sum(-1) > 0).sum()
                if best is None or d < best[0]:
                    best = (d, y)
            y = best[1]
            sp[y:-1] = sp[y + 1:].copy(); sp[-1] = 0         # the legs below move up
        return sp

    def _breath(self, up):
        """Inhale: head and shoulders (rows <= 22) one row up, the neck row repeated."""
        b = up.copy()
        b[0:22] = up[1:23]
        return b

    def _blink(self, up):
        b = up.copy()
        for x, y in ((24, 11), (25, 11), (28, 11)):
            if b[y, x, 3]:
                b[y, x] = rgba("M")
        return b

    def _muzzle(self, out, angle, px, py, size):
        """Code-drawn muzzle flash at the Mazo's striking face (ADR 0001: effects are code)."""
        th = np.radians(angle)
        reach = self.muzzle_reach + 2
        cx, cy = px + reach * np.cos(th), py - reach * np.sin(th)
        star = {1: ["..Y..", ".YlY.", "YlwlY", ".YlY.", "..Y.."],
                2: ["...Y...", "..YlY..", ".YlwlY.", "YlwwwlY", ".YlwlY.", "..YlY..", "...Y..."]}[size]
        h = len(star)
        paint(out, int(round(cx - h // 2)), int(round(cy - h // 2)), [r.replace(".", " ") for r in star])
