// Generated by scripts/music-loop/make-music-loop.ts from reference/audio/music-candidate-2.mp3. Do not edit.
import type { MusicTrack } from './music';

/** The soundtrack: a 16-bar loop at 140 BPM, padded for a seamless buffer-source loop. */
export const MUSIC_TRACK: MusicTrack = {
  file: 'music/theme.mp3',
  loopStart: 0.5,
  loopEnd: 27.928617,
};
